# ./docker-compose.yml

version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cognitopoc
    volumes:
      - ./:/var/www/html:delegated
    ports:
      - 8106:80
    stdin_open: true